### PR TITLE
Prettify Continuity.v a little

### PR DESCRIPTION
**Pull request by Columbus240**
And add SumTopology.v to the _CoqProject file.

### CODE REVIEW

**Comment by Columbus240** [comment]
The results of these CI runs are *very* strange. Both times it compiled on my system without problems. I’ll redo this branch in an hour or two.

**Comment by Columbus240** [comment]
Noo! (In some overly dramatic fashion)
I wanted to squash the TMP commit, before merging the branch.

**Comment by Zimmi48** [comment]
FYI, a good way to mark a PR as not-for-merging on GitHub is to use the "draft PR" feature: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests

**Comment by Columbus240** [comment]
Thanks for mentioning that.

**Pull request merged**
