### PR TITLE
Modernizing for Coq 8.7+

### PR DESCRIPTION
**Pull request by amiloradovsky**
I still didn't manage to fix the Tietze extension theorem,
but nothing else seems to depend on it in this repository.

See also https://github.com/coq-contribs/zorns-lemma/pull/1

### CODE REVIEW

**Comment by herbelin** [comment]
Thanks a lot. I merged your commits 1, 2, 3, 6, and the addition of bullets in 7. I skipped commit 4 (adding path to zorns-lemma) which assumes a layout which has no reason to be same for everyone. We unfortunately both changed master independently, so I skipped commit 5 which was conflictual (in `RationalsInReals.v`) and one line in commit 7.

Side question: would you be interested in moving `zorns-lemma` and `topology` to [coq-community](http://github.com/coq/coq-community) (and, optionally, be the official current maintainer)?

**Comment by amiloradovsky** [comment]
You mean https://github.com/coq-community. — Yes, I think I am interested.
What is the procedure?

**Comment by herbelin** [comment]
@Zimmi48 will correct me if I'm wrong, but I think I just need your ok and then click somewhere to move the repository from here to coq-community. Then, you'll be the maintainer for as long as you want, especially in charge of merging PRs if any, coordinating discussions about PRs if needed, contributing extensions if you wish, proposing collaborative projects around the work, if relevant.

**Comment by Zimmi48** [comment]
Indeed, this is as simple as this, although an additional good first step would be to open an issue at https://github.com/coq-community/manifesto/issues because this will give some publicity to the move.

**Comment by Zimmi48** [comment]
@amiloradovsky: would you like me to proceed with the transfer to coq-community and adding you as the maintainer there?

**Comment by amiloradovsky** [comment]
@Zimmi48 Yes, please.

I was a little busy the last couple weeks. And I'll be away from my main machine(s) for yet another week or so. But generally I have plans regarding integration of some further theory.

**Comment by Zimmi48** [comment]
@amiloradovsky Sorry for the long delay: I have opened https://github.com/coq-community/manifesto/issues/43. Can you confirm there that you are still interested in taking over as official maintainer?

**Pull request closed without merging**
